### ISSUE TITLE
Better way to retrieve credentials

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/nmcp-deploy#3]
**Is your feature request related to a problem? Please describe.**
Currently using a credentials file stored in GCS

**Describe the solution you'd like**
We can store credentials using AWS Secrets Manager and grant the EC2 instance permission to retrieve the secret. This will require updating the codebase to use an api to download the creds.

**Describe alternatives you've considered**

**Additional context**

**Comment by pedson** [comment]
The container is currently able to write the S3 buckets from the EC2 instances.  A couple remaining issues seem to be that a) it cannot delete objects in the bucket (e.g., clean up after a dataset rotation) and b) Neuroglancer returns `Fetching "
https://aind-neuron-morphology-community-portal-dev-u5u0i5.s3.amazonaws.com/info"
resulted in HTTP error 0: Network or CORS error.` when trying to access as a public bucket.

**Comment by pedson** [comment]
Everything appears functional!
